In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('train.csv')

In [ ]:
df

id  ... label
0          0  ...     1
1          1  ...     0
2          2  ...     1
3          3  ...     1
4          4  ...     1
...      ...  ...   ...
20795  20795  ...     0
20796  20796  ...     0
20797  20797  ...     0
20798  20798  ...     1
20799  20799  ...     1

[20800 rows x 5 columns]

In [ ]:
df = df.dropna()

In [ ]:
df

id  ... label
0          0  ...     1
1          1  ...     0
2          2  ...     1
3          3  ...     1
4          4  ...     1
...      ...  ...   ...
20795  20795  ...     0
20796  20796  ...     0
20797  20797  ...     0
20798  20798  ...     1
20799  20799  ...     1

[18285 rows x 5 columns]

In [ ]:
X = df.drop('label', axis = 1)
X

id  ...                                               text
0          0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1          1  ...  Ever get the feeling your life circles the rou...
2          2  ...  Why the Truth Might Get You Fired October 29, ...
3          3  ...  Videos 15 Civilians Killed In Single US Airstr...
4          4  ...  Print \nAn Iranian woman has been sentenced to...
...      ...  ...                                                ...
20795  20795  ...  Rapper T. I. unloaded on black celebrities who...
20796  20796  ...  When the Green Bay Packers lost to the Washing...
20797  20797  ...  The Macy’s of today grew from the union of sev...
20798  20798  ...  NATO, Russia To Hold Parallel Exercises In Bal...
20799  20799  ...    David Swanson is an author, activist, journa...

[18285 rows x 4 columns]

In [ ]:
Y = df['label']
Y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [ ]:
X.shape

(18285, 4)

In [ ]:
Y.shape

(18285,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.5.0'

In [ ]:
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
input_text = 5000

In [ ]:
m = X.copy()

In [ ]:
m

id  ...                                               text
0          0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1          1  ...  Ever get the feeling your life circles the rou...
2          2  ...  Why the Truth Might Get You Fired October 29, ...
3          3  ...  Videos 15 Civilians Killed In Single US Airstr...
4          4  ...  Print \nAn Iranian woman has been sentenced to...
...      ...  ...                                                ...
20795  20795  ...  Rapper T. I. unloaded on black celebrities who...
20796  20796  ...  When the Green Bay Packers lost to the Washing...
20797  20797  ...  The Macy’s of today grew from the union of sev...
20798  20798  ...  NATO, Russia To Hold Parallel Exercises In Bal...
20799  20799  ...    David Swanson is an author, activist, journa...

[18285 rows x 4 columns]

In [ ]:
m=m['title']

In [ ]:
m

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                        Why the Truth Might Get You Fired
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...                        
20795    Rapper T.I.: Trump a ’Poster Child For White S...
20796    N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797    Macy’s Is Said to Receive Takeover Approach by...
20798    NATO, Russia To Hold Parallel Exercises In Bal...
20799                            What Keeps the F-35 Alive
Name: title, Length: 18285, dtype: object

In [ ]:
m.reset_index(inplace=True)

TypeError: ignored

In [ ]:
m.reset_index(inplace=True)

In [ ]:
m['title'][9]

'BBC Comedy Sketch "Real Housewives of ISIS" Causes Outrage'

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
corpus = []
for i in range(0, len(m)):
  print(i) ## to check the speed 
  review = re.sub('[^a-zA-Z]', ' ', m['title'][i])
  review = review.lower()
  review = review.split() ## split func because we have to use remove stopwords

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)









Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
for words in corpus:
  print(words)
 

Streaming output truncated to the last 5000 lines.
mitch mcconnel paul ryan meet donald trump promis bold agenda breitbart
susan rice ex obama advis back polit cross hair surveil new york time
fix nbc affili accident post elect result week earli hillari win presid trump
origin unreleas transcript sonia gandhi interview rajdeep sardesai obtain
indian man accus multimillion dollar call center swindl held new york time
teenag death answer aborigin canadian new york time
fashion cast iron pan today cook new york time
summer sweat hollywood brace possibl worst box offic decad
trump execut order target trade abus amid nafta intrigu breitbart
new york time moscow bureau target hacker new york time
barbra streisand say sexism cost multipl oscar nomin
comey investig red her cover wikileak dump
gorsuch tri put polit confirm hear new york time
kelsey hark women striker ignor atroc muslim world
ken adachi trump win
ted cruz call billion seiz el chapo fund border wall
new earthquak rock itali build

In [ ]:
## One hot encoding of text

In [ ]:
one = [ one_hot(input_text = words, n=input_text ) for words in corpus ]
one

[[928, 1612, 3554, 1652, 1945, 1846, 1021, 3562, 1437, 1620],
 [3038, 4977, 2079, 2734, 923, 1918, 3893],
 [4287, 4264, 796, 130],
 [3708, 1117, 1882, 2898, 2694, 1159],
 [2692, 923, 342, 126, 4687, 1617, 923, 1566, 4171, 3314],
 [4709,
  4671,
  897,
  3854,
  1004,
  3783,
  1448,
  3483,
  3782,
  914,
  1957,
  4857,
  33,
  4105,
  3893],
 [3666, 3807, 302, 1304, 879, 2537, 4361, 2875, 3464, 3543, 207],
 [139, 3475, 1868, 855, 3637, 4548, 3783, 2475, 3464, 3543, 207],
 [1674, 4280, 2080, 4926, 1176, 3871, 674, 546, 3783, 4626],
 [2625, 3488, 649, 4941, 3110, 2032, 1749, 494],
 [2801, 1032, 3471, 1468, 1622, 2217, 4185, 1102, 680, 4361, 4105],
 [2898, 4819, 1945, 3871, 3783, 3637],
 [2469, 2943, 1601, 2670, 970, 2987, 741, 3668, 2756],
 [3164, 4581, 1542, 4604, 2202, 3916, 1031, 3464, 3543, 207],
 [2706, 3613, 2506, 707, 1892, 3464, 3543, 207],
 [1519, 241, 839, 877, 1640, 4762, 2836, 3163, 736, 817],
 [3166, 2154, 4977],
 [4537, 704, 1062, 4656, 3783, 3602, 3302, 3893],
 [3621, 16

In [ ]:
len(one)

18285

In [ ]:
## Embedding Representation

In [ ]:
l = 20
embedded_docs = pad_sequences(one,maxlen=l,padding='pre')
print(embedded_docs)

[[   0    0    0 ... 3562 1437 1620]
 [   0    0    0 ...  923 1918 3893]
 [   0    0    0 ... 4264  796  130]
 ...
 [   0    0    0 ... 3464 3543  207]
 [   0    0    0 ... 4511  939 3332]
 [   0    0    0 ... 1895 1298 2360]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  928,
       1612, 3554, 1652, 1945, 1846, 1021, 3562, 1437, 1620], dtype=int32)

In [ ]:
## creating model 

dim = 40 
model = Sequential()
model.add(Embedding(input_text ,dim,input_length = l ))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam', metrics = ['accuracy'])
model.summary()


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [ ]:
len(embedded_docs), Y.shape

(18285, (18285,))

In [ ]:
embedded_docs


array([[   0,    0,    0, ..., 3562, 1437, 1620],
       [   0,    0,    0, ...,  923, 1918, 3893],
       [   0,    0,    0, ..., 4264,  796,  130],
       ...,
       [   0,    0,    0, ..., 3464, 3543,  207],
       [   0,    0,    0, ..., 4511,  939, 3332],
       [   0,    0,    0, ..., 1895, 1298, 2360]], dtype=int32)

In [ ]:
import numpy as np

## for train test split
X_final = np.array(embedded_docs)
Y_final = np.array(Y)

In [ ]:
X_final

array([[   0,    0,    0, ..., 3562, 1437, 1620],
       [   0,    0,    0, ...,  923, 1918, 3893],
       [   0,    0,    0, ..., 4264,  796,  130],
       ...,
       [   0,    0,    0, ..., 3464, 3543,  207],
       [   0,    0,    0, ..., 4511,  939, 3332],
       [   0,    0,    0, ..., 1895, 1298, 2360]], dtype=int32)

In [ ]:
X_final.shape , Y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(X_final , Y_final , test_size = 0.33 , random_state = 0) 

In [ ]:
x_train.shape

(12250, 20)

In [ ]:
## Model Training  


In [ ]:
model.fit(x_train , y_train , validation_data= (x_test, y_test) , epochs = 10 , batch_size = 64)

Epoch 1/10
192/192 [==============================] - 9s 37ms/step - loss: 0.3297 - accuracy: 0.8431 - val_loss: 0.1867 - val_accuracy: 0.9191
Epoch 2/10
192/192 [==============================] - 6s 32ms/step - loss: 0.1394 - accuracy: 0.9458 - val_loss: 0.1884 - val_accuracy: 0.9218
Epoch 3/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0995 - accuracy: 0.9644 - val_loss: 0.2216 - val_accuracy: 0.9171
Epoch 4/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0760 - accuracy: 0.9729 - val_loss: 0.2512 - val_accuracy: 0.9165
Epoch 5/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0581 - accuracy: 0.9812 - val_loss: 0.2502 - val_accuracy: 0.9127
Epoch 6/10
192/192 [==============================] - 7s 34ms/step - loss: 0.0468 - accuracy: 0.9837 - val_loss: 0.2870 - val_accuracy: 0.9163
Epoch 7/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0388 - accuracy: 0.9873 - val_loss: 0.3649 - val_accuracy: 0.9089

In [ ]:
## Adding dropout : to increase val accuray 

In [ ]:
from tensorflow.keras.layers import Dropout

dim = 40 
model = Sequential()
model.add(Embedding(input_text ,dim,input_length = l ))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam', metrics = ['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
dropout_2 (Dropout)          (None, 20, 40)            0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dropout_3 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x_train , y_train , validation_data= (x_test, y_test) , epochs = 10 , batch_size = 64)

Epoch 1/10
192/192 [==============================] - 8s 35ms/step - loss: 0.3476 - accuracy: 0.8321 - val_loss: 0.1943 - val_accuracy: 0.9162
Epoch 2/10
192/192 [==============================] - 6s 33ms/step - loss: 0.1510 - accuracy: 0.9394 - val_loss: 0.1951 - val_accuracy: 0.9196
Epoch 3/10
192/192 [==============================] - 6s 33ms/step - loss: 0.1080 - accuracy: 0.9602 - val_loss: 0.2166 - val_accuracy: 0.9196
Epoch 4/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0858 - accuracy: 0.9696 - val_loss: 0.2436 - val_accuracy: 0.9017
Epoch 5/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0720 - accuracy: 0.9751 - val_loss: 0.2489 - val_accuracy: 0.9140
Epoch 6/10
192/192 [==============================] - 6s 34ms/step - loss: 0.0563 - accuracy: 0.9812 - val_loss: 0.2981 - val_accuracy: 0.9168
Epoch 7/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0481 - accuracy: 0.9844 - val_loss: 0.3094 - val_accuracy: 0.9153

In [ ]:
y_pred= model.predict_classes(x_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
y_pred

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [ ]:
from sklearn.metrics import confusion_matrix


In [ ]:
confusion_matrix(y_test,y_pred)

array([[3110,  279],
       [ 268, 2378]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9093620546810274